[versions]
activityCompose = "1.9.1"
composeBom = "2024.06.00"
composeUiVersion = "1.6.8"
coreKtx = "1.13.1"
espressoCore = "3.6.1"
jna = "5.14.0"
junitVersion = "1.2.1"
junit = "4.13.2"
kotlinxCoroutinesCore = "1.8.1"
ktorServer = "2.3.12"
lifecycleRuntimeKtx = "2.8.4"
navigationCompose = "2.7.7"
okhttp = "5.0.0-alpha.14"
room = "2.6.1"
storage = "1.5.5"
workRuntimeKtx = "2.9.1"
material3 = "1.2.1"
quartz = "0.89.9"
kotlin = "2.0.0"
agp = "8.5.2"
ksp = "2.0.0-1.0.22"
ktlint = "12.1.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUiVersion" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "composeUiVersion" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "composeUiVersion" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeUiVersion" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUiVersion" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUiVersion" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktorServer" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktorServer" }
ktor-websockets = { module = "io.ktor:ktor-websockets", version.ref = "ktorServer" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktorServer" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
quartz = { module = "com.github.vitorpamplona.amethyst:quartz", version.ref = "quartz" }
ammolite = { module = "com.github.vitorpamplona.amethyst:ammolite", version.ref = "quartz" }
storage = { module = "com.anggrayudi:storage", version.ref = "storage" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }

[plugins]
jetbrainsComposeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kt-lint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
