[versions]
activityCompose = "1.11.0"
composeBom = "2025.11.00"
composeUiVersion = "1.9.4"
iconsExtended = "1.7.8"
coreKtx = "1.17.0"
espressoCore = "3.7.0"
jna = "5.18.1"
junitVersion = "1.3.0"
junit = "4.13.2"
kotlinxCoroutinesCore = "1.10.2"
ktorServer = "3.3.2"
lifecycleRuntimeKtx = "2.9.4"
navigationCompose = "2.9.6"
okhttp = "5.3.1"
room = "2.8.3"
storage = "2.2.0"
workRuntimeKtx = "2.11.0"
material3 = "1.4.0"
quartz = "1.04.2"
kotlin = "2.2.21"
agp = "8.13.1"
ksp = "2.3.2"
ktlint = "14.0.1"
securityCryptoKtx = "1.1.0"
collections = "0.4.0"
pagingCommon = "3.3.6"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUiVersion" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "composeUiVersion" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "iconsExtended" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeUiVersion" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUiVersion" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUiVersion" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktorServer" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktorServer" }
ktor-websockets = { module = "io.ktor:ktor-websockets", version.ref = "ktorServer" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktorServer" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
quartz = { module = "com.vitorpamplona.quartz:quartz-android", version.ref = "quartz" }
storage = { module = "com.anggrayudi:storage", version.ref = "storage" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
security-crypto-ktx = { module = "androidx.security:security-crypto-ktx", version.ref = "securityCryptoKtx" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "collections" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "pagingCommon" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "pagingCommon" }
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "pagingCommon" }

[plugins]
jetbrainsComposeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kt-lint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
